# Project for Getting and Cleaning Data

Author: Raj Sengodan


## Objective

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.

## Steps to reproduce this project

* Open the R script run_analysis.R using a text editor.
* Change the parameter of the setwd function call to the working directory/folder (i.e., the folder where these the R script file is saved).
* Download the required dataset in the working directory
* Run the R script run_analysis.R. It calls the R Markdown file, run_analysis.Rmd, which contains the bulk of the code.

## Outputs produced

* Tidy dataset file Result.txt (tab-delimited text)
* Codebook file codebook.md (Markdown)
